Fix post-review when used for perforce paths.
Commit 58ccae27 added a new argument to _do_diff() but didn't account
for it with this caller...

https://github.com/reviewboard/rbtools/commit/58ccae27

As a result posting a code review using a path results in a
stacktrace...

http://code.google.com/p/reviewboard/issues/detail?id=%202881

% post-review //path/to/my/file
Traceback (most recent call last):
  File "/share/rbtools/postreview.py", line 1469, in <module>
    main()
  File "/share/rbtools/postreview.py", line 1407, in main
    diff, parent_diff = tool.diff(args)
  File "/share/rbtools/clients/perforce.py", line 290, in diff
    return self._path_diff(args)
  File "/share/rbtools/clients/perforce.py", line 414, in _path_diff
    ignore_unmodified=True)
TypeError: _do_diff() takes at least 7 non-keyword arguments (6 given)

This fixes the crashing, but eventually this code will need to be
updated to support moved files as well.

Reviewed at http://reviews.reviewboard.org/r/4150/