Avoid error in rbtools.clients.tfs if "tf" returns 1
If "tf" returns 1, the TFS client may error out with:

```
ERROR: Could not load SCM Client "tfs"
Traceback (most recent call last):
  File "[...]/rbtools/clients/__init__.py", line 397, in load_scmclients
    client = ep.load()(config=config, options=options)
  File "[...]/rbtools/clients/tfs.py", line 972, in __init__
    if 'Version Control Tool, Version 15' in tf_vc_output:
TypeError: argument of type 'NoneType' is not iterable
```

because of `none_on_ignored_error=True` immediately above.

Testing Done:
Ran unit tests

Reviewed at https://reviews.reviewboard.org/r/9995/