Fix --repository-url handling for Git.
There were several problems:

(1) If --repository-url was used, post-review failed with
    UnboundLocalError: local variable 'origin_url' reference before
    assignment

    Fixed by using this code only in the autodetection case.

(2) self.upstream branch wasn't always set, thus failing later.

(3) The parameter was ignored completely when using git-svn.

Reviewed at http://reviews.reviewboard.org/r/2647/