Work around OS X 10.11 bug with check_install()
This has been fixed upstream (http://bugs.python.org/issue26083) but who knows
when Apple will update their version of Python they distribute so this change
simply works around the issue by treating a ValueError to be the same as an
OSError.

Testing Done:
Before my fix, when running rbt post, I get:
  ValueError: insecure string pickle
(I don't have tfs installed)

After my fix, running rbt post works fine.

Reviewed at https://reviews.reviewboard.org/r/8058/